sonar.projectKey=jakeer.com
sonar.projectName=jakeer.com
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/__tests__/**/*.test.tsx,src/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,.next/**,**/*.config.*,coverage/**
