sonar.projectKey=jakeer.com
sonar.projectName=jakeer.com
sonar.organization=jakeerc
# Uncomment and update the line below if you are using a self-hosted SonarQube server instead of SonarCloud
# sonar.host.url=http://localhost:9000
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/__tests__/**/*.test.tsx,src/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,.next/**,**/*.config.*,coverage/**
